In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 1000)


## Important

AREA, ANGLE and REL have missing data.

In [2]:
# Just load the dataset
dd_df = pd.read_sas("/Users/gomerudo/workspace/SAS/SASUniversityEdition/myfolders/datasetsBD/assignment_dd.sas7bdat")

dd_df['ID'] = dd_df['ID'].astype('int')
dd_df['FU'] = dd_df['FU'].astype('int')
dd_df['Hand'] = dd_df['Hand'].astype('int')
dd_df['SEX'] = dd_df['SEX'].astype('int')
dd_df['SMOKE'] = dd_df['SMOKE'].astype('int')
dd_df['ALC'] = dd_df['ALC'].astype('int')
dd_df['INJ'] = dd_df['INJ'].astype('int')
dd_df['DIA'] = dd_df['DIA'].astype('int')
dd_df['EPI'] = dd_df['EPI'].astype('int')
dd_df['LIV'] = dd_df['LIV'].astype('int')
#dd_df['REL'] = dd_df['REL'].astype('int')
dd_df['DD'] = dd_df['DD'].astype('int')

dd_df.head()

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
0   2   0     0   0.000000    0  81.0      1    1    0    0    0    0  1.0   
1   2   0     1   0.000000    0  81.0      1    1    0    0    0    0  1.0   
2   2   1     0   5.753425    0  81.0      1    1    0    0    0    0  1.0   
3   2   1     1   5.753425    0  81.0      1    1    0    0    0    0  1.0   
4   2   2     0  11.736986    0  81.0      1    1    0    0    0    0  1.0   

   DD  AREA  ANGLE  
0   1  3.63    0.0  
1   1  3.33    0.0  
2   1  2.57    0.0  
3   1  2.19    0.0  
4   1  2.50    0.0

In [3]:
# Fill missing values with -1, since groupby remove NaN values. 
# This way we can see how many patients with missinga data in column REL we have.

dd_df = dd_df.fillna(-1)
grouped = dd_df.groupby(['ID', 'REL'])
grouped.count()

FU  Hand  MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  DD  \
ID  REL                                                                    
2    0.0   2     2      2    2     2      2    2    2    2    2    2   2   
     1.0  18    18     18   18    18     18   18   18   18   18   18  18   
3    1.0  20    20     20   20    20     20   20   20   20   20   20  20   
4    1.0  16    16     16   16    16     16   16   16   16   16   16  16   
6    0.0  14    14     14   14    14     14   14   14   14   14   14  14   
7    0.0  20    20     20   20    20     20   20   20   20   20   20  20   
8    1.0  10    10     10   10    10     10   10   10   10   10   10  10   
9   -1.0   1     1      1    1     1      1    1    1    1    1    1   1   
     0.0   8     8      8    8     8      8    8    8    8    8    8   8   
10   0.0  12    12     12   12    12     12   12   12   12   12   12  12   
11   0.0  12    12     12   12    12     12   12   12   12   12   12  12   
12   0.0  14    14     14   14    14     14   14   14   14   14   14  14   
     1.0   6     6      6    6     6      6    6    6    6    6    6   6   
14   0.0  10    10     10   10    10     10   10   10   10   10   10  10   
15   0.0   3     3      3    3     3      3    3    3    3    3    3   3   
16   1.0   6     6      6    6     6      6    6    6    6    6    6   6   
17   0.0   6     6      6    6     6      6    6    6    6    6    6   6   
19   0.0  10    10     10   10    10     10   10   10   10   10   10  10   
20  -1.0   1     1      1    1     1      1    1    1    1    1    1   1   
     1.0   9     9      9    9     9      9    9    9    9    9    9   9   
21   0.0   6     6      6    6     6      6    6    6    6    6    6   6   
23   0.0   6     6      6    6     6      6    6    6    6    6    6   6   
24   0.0  14    14     14   14    14     14   14   14   14   14   14  14   
     1.0   2     2      2    2     2      2    2    2    2    2    2   2   
25   0.0   4     4      4    4     4      4    4    4    4    4    4   4   
26   1.0  10    10     10   10    10     10   10   10   10   10   10  10   
27   1.0  18    18     18   18    18     18   18   18   18   18   18  18   
28   1.0  18    18     18   18    18     18   18   18   18   18   18  18   
30   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
31   1.0  10    10     10   10    10     10   10   10   10   10   10  10   
32   0.0   6     6      6    6     6      6    6    6    6    6    6   6   
     1.0  10    10     10   10    10     10   10   10   10   10   10  10   
33   1.0  18    18     18   18    18     18   18   18   18   18   18  18   
34   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
35   0.0   4     4      4    4     4      4    4    4    4    4    4   4   
     1.0  16    16     16   16    16     16   16   16   16   16   16  16   
36   1.0  10    10     10   10    10     10   10   10   10   10   10  10   
37   0.0  10    10     10   10    10     10   10   10   10   10   10  10   
38   0.0   4     4      4    4     4      4    4    4    4    4    4   4   
     1.0  12    12     12   12    12     12   12   12   12   12   12  12   
40   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
41   1.0  10    10     10   10    10     10   10   10   10   10   10  10   
42   1.0  20    20     20   20    20     20   20   20   20   20   20  20   
44   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
45   1.0  10    10     10   10    10     10   10   10   10   10   10  10   
46   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
47   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
48   1.0  20    20     20   20    20     20   20   20   20   20   20  20   
49   0.0   2     2      2    2     2      2    2    2    2    2    2   2   
50   0.0  20    20     20   20    20     20   20   20   20   20   20  20   
51   0.0  20    20     20   20    20     20   20   20   20

In [4]:
dd_df = dd_df.fillna(-1)

filtered1 = dd_df[dd_df['AREA'] < 0]
filtered1

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
103     9   2     1  17.753425    0  59.0      1    1    0    0    0    0   
1020   85   8     0  45.961644    0  60.0      1    1    0    0    0    0   
1141   97   5     0  35.802740    1  57.0      0    1    1    0    0    0   
1992  174   8     0  45.928767    0  67.0      1    1    1    1    0    0   
2238  199   7     1  43.298630    1  62.0      0    1    1    0    0    0   

      REL  DD  AREA  ANGLE  
103  -1.0   1  -1.0   -1.0  
1020  1.0   1  -1.0   -1.0  
1141  1.0   1  -1.0   -1.0  
1992 -1.0   1  -1.0   -1.0  
2238  0.0   1  -1.0   -1.0

In [5]:
dd_df = dd_df.fillna(-1)

filtered2 = dd_df[dd_df['ANGLE'] < 0]
filtered2

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
103     9   2     1  17.753425    0  59.0      1    1    0    0    0    0   
1020   85   8     0  45.961644    0  60.0      1    1    0    0    0    0   
1141   97   5     0  35.802740    1  57.0      0    1    1    0    0    0   
1992  174   8     0  45.928767    0  67.0      1    1    1    1    0    0   
2238  199   7     1  43.298630    1  62.0      0    1    1    0    0    0   

      REL  DD  AREA  ANGLE  
103  -1.0   1  -1.0   -1.0  
1020  1.0   1  -1.0   -1.0  
1141  1.0   1  -1.0   -1.0  
1992 -1.0   1  -1.0   -1.0  
2238  0.0   1  -1.0   -1.0

## Analysis of AREA and ANGLE missing data

Good thing: area and angle are missing in the same ID's! :D

In [7]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 9]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
100   9   0     0   0.000000    0  59.0      0    1    1    0    0    0  0.0   
101   9   0     1   0.000000    0  59.0      0    1    0    0    0    0  0.0   
102   9   1     1  14.235616    0  59.0      1    1    0    0    0    0  0.0   
103   9   2     1  17.753425    0  59.0      1    1    0    0    0    0 -1.0   
104   9   3     1  19.561644    0  59.0      1    1    0    0    0    0  0.0   
105   9   4     1  24.789041    0  59.0      1    1    0    0    0    0  0.0   
106   9   5     1  30.378082    0  59.0      1    1    0    0    0    0  0.0   
107   9   6     1  37.676712    0  59.0      1    1    0    0    0    0  0.0   
108   9   7     1  42.279452    0  59.0      1    1    0    0    0    0  0.0   

     DD    AREA  ANGLE  
100   1   9.610  115.0  
101   1   6.707   16.0  
102   1   9.314    8.0  
103   1  -1.000   -1.0  
104   1   9.988    6.0  
105   1  11.211   62.0  
106   1  12.599   24.0  
107   1  14.418   34.0  
108   1  11.782  102.0

In [8]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 85]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
1012  85   0     0   0.000000    0  60.0      1    1    0    0    0    0  0.0   
1013  85   1     0   5.687671    0  60.0      1    1    0    0    0    0  0.0   
1014  85   2     0  14.432877    0  60.0      1    1    0    0    0    0  0.0   
1015  85   3     0  18.641096    0  60.0      1    1    0    0    0    0  0.0   
1016  85   4     0  24.460274    0  60.0      1    1    0    0    0    0  0.0   
1017  85   5     0  30.673973    0  60.0      1    1    0    0    0    0  1.0   
1018  85   6     0  38.268493    0  60.0      1    1    0    0    0    0  1.0   
1019  85   7     0  41.950685    0  60.0      1    1    0    0    0    0  1.0   
1020  85   8     0  45.961644    0  60.0      1    1    0    0    0    0  1.0   
1021  85   9     0  47.243836    0  60.0      1    1    0    0    0    0  1.0   
1022  85  10     0  53.687671    0  60.0      1    1    0    0    0    0  1.0   

      DD   AREA  ANGLE  
1012   1  3.250    0.0  
1013   1  2.000    0.0  
1014   1  3.067    0.0  
1015   1  2.880    0.0  
1016   1  3.467    0.0  
1017   1  3.507    0.0  
1018   1  3.700    0.0  
1019   1  4.040    4.0  
1020   1 -1.000   -1.0  
1021   1  4.707    0.0  
1022   1  3.160    0.0

In [9]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 97]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
1136  97   0     0   0.000000    1  57.0      0    1    1    0    0    0  1.0   
1137  97   1     0   9.205479    1  57.0      0    1    1    0    0    0  1.0   
1138  97   2     0  12.230137    1  57.0      0    1    1    0    0    0  1.0   
1139  97   3     0  18.706849    1  57.0      0    1    1    0    0    0  1.0   
1140  97   4     0  31.298630    1  57.0      0    1    1    0    0    0  1.0   
1141  97   5     0  35.802740    1  57.0      0    1    1    0    0    0  1.0   
1142  97   6     0  39.649315    1  57.0      0    1    1    0    0    0  1.0   

      DD    AREA  ANGLE  
1136   1   9.350    0.0  
1137   1  11.355    0.0  
1138   1  11.608    0.0  
1139   1   9.609    0.0  
1140   1  11.806    6.0  
1141   1  -1.000   -1.0  
1142   1  10.840   62.0

In [10]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 174]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
1984  174   0     0   0.000000    0  67.0      1    1    1    0    0    0   
1985  174   1     0   5.983562    0  67.0      1    1    1    0    0    0   
1986  174   2     0  11.934247    0  67.0      1    1    1    0    0    0   
1987  174   3     0  17.917808    0  67.0      1    1    1    0    0    0   
1988  174   4     0  23.901370    0  67.0      1    1    1    0    0    0   
1989  174   5     0  30.542466    0  67.0      1    1    1    0    0    0   
1990  174   6     0  36.295890    0  67.0      1    1    1    1    0    0   
1991  174   7     0  41.326027    0  67.0      1    1    1    1    0    0   
1992  174   8     0  45.928767    0  67.0      1    1    1    1    0    0   
1993  174   9     0  46.717808    0  67.0      1    1    1    1    0    0   
1994  174  10     0  53.884932    0  67.0      1    1    1    1    0    0   

      REL  DD  AREA  ANGLE  
1984  0.0   1  0.35    0.0  
1985  0.0   1  0.45    0.0  
1986  0.0   1  0.70    0.0  
1987  0.0   1  0.35    0.0  
1988  0.0   1  0.13    0.0  
1989  0.0   1  0.40    0.0  
1990  0.0   1  0.50    0.0  
1991  0.0   1  0.69    0.0  
1992 -1.0   1 -1.00   -1.0  
1993  0.0   1  0.50    0.0  
1994  0.0   1  0.50    0.0

In [11]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 199]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
2231  199   0     1   0.000000    1  62.0      0    1    1    0    0    0   
2232  199   1     1   6.016438    1  62.0      0    1    1    0    0    0   
2233  199   2     1  13.084932    1  62.0      0    1    1    0    0    0   
2234  199   3     1  19.298630    1  62.0      0    1    1    0    0    0   
2235  199   4     1  25.315068    1  62.0      0    1    1    0    0    0   
2236  199   5     1  31.561644    1  62.0      0    1    1    0    0    0   
2237  199   6     1  38.926027    1  62.0      0    1    1    0    0    0   
2238  199   7     1  43.298630    1  62.0      0    1    1    0    0    0   
2239  199   8     1  49.380822    1  62.0      0    1    1    0    0    0   
2240  199   9     1  53.786301    1  62.0      0    1    1    0    0    0   

      REL  DD   AREA  ANGLE  
2231  0.0   1  0.800    0.0  
2232  0.0   1  1.200    0.0  
2233  0.0   1  1.470    0.0  
2234  0.0   1  2.123    0.0  
2235  0.0   1  2.977    0.0  
2236  0.0   1  3.843    0.0  
2237  0.0   1  4.617    0.0  
2238  0.0   1 -1.000   -1.0  
2239  0.0   1  3.375    0.0  
2240  0.0   1  3.587    0.0

## Analysis of the REL missing values

From this analysis, 3 relevant things:

- There are 8 patients with missing values in REL: 9, 20, 151, 174, 177, 179, 183, 243
- There are patients with measurements in only one hand, others in both hands and others that stopped the follow-up for only 1 hand.
- Sometimes they report to have a relative with DD in the middle of the follow up, and in the next follow up they say that they do not have. This is clearly an inconsistency we should fix. There are 30 with this inconsistency!!

### Possible solution:

- Replace "manually". This is more an inconsistency than a missing value problem.

In [12]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 9]


ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
100   9   0     0   0.000000    0  59.0      0    1    1    0    0    0  0.0   
101   9   0     1   0.000000    0  59.0      0    1    0    0    0    0  0.0   
102   9   1     1  14.235616    0  59.0      1    1    0    0    0    0  0.0   
103   9   2     1  17.753425    0  59.0      1    1    0    0    0    0 -1.0   
104   9   3     1  19.561644    0  59.0      1    1    0    0    0    0  0.0   
105   9   4     1  24.789041    0  59.0      1    1    0    0    0    0  0.0   
106   9   5     1  30.378082    0  59.0      1    1    0    0    0    0  0.0   
107   9   6     1  37.676712    0  59.0      1    1    0    0    0    0  0.0   
108   9   7     1  42.279452    0  59.0      1    1    0    0    0    0  0.0   

     DD    AREA  ANGLE  
100   1   9.610  115.0  
101   1   6.707   16.0  
102   1   9.314    8.0  
103   1  -1.000   -1.0  
104   1   9.988    6.0  
105   1  11.211   62.0  
106   1  12.599   24.0  
107   1  14.418   34.0  
108   1  11.782  102.0

In [13]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 20]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  \
188  20   0     0   0.000000    1  57.0      1    1    0    0    0    0  1.0   
189  20   1     0   6.213699    1  57.0      1    1    0    0    0    0  1.0   
190  20   2     0  12.263014    1  57.0      1    1    0    0    0    0  1.0   
191  20   3     0  18.443836    1  57.0      1    1    0    0    0    0  1.0   
192  20   4     0  24.197260    1  57.0      1    1    0    0    0    0  1.0   
193  20   5     0  30.180822    1  57.0      1    1    0    0    0    0  1.0   
194  20   6     0  35.473973    1  57.0      1    1    0    0    0    0  1.0   
195  20   7     0  41.457534    1  57.0      1    1    0    0    0    0 -1.0   
196  20   8     0  49.282192    1  57.0      1    1    0    0    0    0  1.0   
197  20   9     0  53.424658    1  57.0      1    1    0    0    0    0  1.0   

     DD   AREA  ANGLE  
188   0  0.000    0.0  
189   1  0.300    0.0  
190   1  0.340    0.0  
191   1  0.275    0.0  
192   1  1.480    0.0  
193   1  1.030    0.0  
194   1  1.340    0.0  
195   1  1.270    0.0  
196   1  1.137    0.0  
197   1  1.563    0.0

In [14]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 151]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
1719  151   0     0   0.000000    0  75.0      1    1    0    0    0    0   
1720  151   0     1   0.000000    0  75.0      1    1    0    0    0    0   
1721  151   1     0   4.964384    0  75.0      1    1    0    0    0    0   
1722  151   1     1   4.964384    0  75.0      1    1    0    0    0    0   
1723  151   2     0  10.882192    0  75.0      1    1    0    0    0    0   
1724  151   2     1  10.882192    0  75.0      1    1    0    0    0    0   
1725  151   3     0  16.865753    0  75.0      1    1    0    0    0    0   
1726  151   3     1  16.865753    0  75.0      1    1    0    0    0    0   
1727  151   4     0  22.849315    0  75.0      1    1    0    0    0    0   
1728  151   4     1  22.849315    0  75.0      1    1    0    0    0    0   
1729  151   5     0  25.315068    0  75.0      1    1    0    0    0    0   
1730  151   5     1  25.315068    0  75.0      1    1    0    0    0    0   
1731  151   6     0  28.142466    0  75.0      1    1    0    0    0    0   
1732  151   7     0  34.126027    0  75.0      1    1    0    0    0    0   
1733  151   8     0  40.142466    0  75.0      1    1    0    0    0    0   
1734  151   9     0  46.553425    0  75.0      1    1    0    0    0    0   

      REL  DD   AREA  ANGLE  
1719  0.0   1  4.723   10.0  
1720  0.0   1  2.660   35.0  
1721  0.0   1  3.760   14.0  
1722  0.0   1  4.567   42.0  
1723  0.0   1  4.810   16.0  
1724  0.0   1  4.290    0.0  
1725  0.0   1  4.875   16.0  
1726  0.0   1  3.850   52.0  
1727  0.0   1  5.195    0.0  
1728  0.0   1  3.187   64.0  
1729 -1.0   1  5.830    0.0  
1730 -1.0   1  4.417   62.0  
1731  0.0   1  5.980   10.0  
1732  0.0   1  6.465   18.0  
1733  0.0   1  6.985   14.0  
1734  0.0   1  6.250   14.0

In [15]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 174]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
1984  174   0     0   0.000000    0  67.0      1    1    1    0    0    0   
1985  174   1     0   5.983562    0  67.0      1    1    1    0    0    0   
1986  174   2     0  11.934247    0  67.0      1    1    1    0    0    0   
1987  174   3     0  17.917808    0  67.0      1    1    1    0    0    0   
1988  174   4     0  23.901370    0  67.0      1    1    1    0    0    0   
1989  174   5     0  30.542466    0  67.0      1    1    1    0    0    0   
1990  174   6     0  36.295890    0  67.0      1    1    1    1    0    0   
1991  174   7     0  41.326027    0  67.0      1    1    1    1    0    0   
1992  174   8     0  45.928767    0  67.0      1    1    1    1    0    0   
1993  174   9     0  46.717808    0  67.0      1    1    1    1    0    0   
1994  174  10     0  53.884932    0  67.0      1    1    1    1    0    0   

      REL  DD  AREA  ANGLE  
1984  0.0   1  0.35    0.0  
1985  0.0   1  0.45    0.0  
1986  0.0   1  0.70    0.0  
1987  0.0   1  0.35    0.0  
1988  0.0   1  0.13    0.0  
1989  0.0   1  0.40    0.0  
1990  0.0   1  0.50    0.0  
1991  0.0   1  0.69    0.0  
1992 -1.0   1 -1.00   -1.0  
1993  0.0   1  0.50    0.0  
1994  0.0   1  0.50    0.0

In [16]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 177]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
1995  177   0     0   0.000000    0  66.0      1    1    0    0    0    0   
1996  177   0     1   0.000000    0  66.0      1    1    0    0    0    0   
1997  177   1     0   6.838356    0  66.0      1    1    0    0    0    0   
1998  177   1     1   6.838356    0  66.0      1    1    0    0    0    0   
1999  177   2     0  12.394521    0  66.0      1    1    0    0    0    0   
2000  177   2     1  12.394521    0  66.0      1    1    0    0    0    0   
2001  177   3     0  18.378082    0  66.0      1    1    0    0    0    0   
2002  177   3     1  18.378082    0  66.0      1    1    0    0    0    0   
2003  177   4     0  23.868493    0  66.0      1    1    0    0    0    0   

      REL  DD    AREA  ANGLE  
1995 -1.0   1  13.608    0.0  
1996 -1.0   1   6.630    0.0  
1997 -1.0   1  10.303   31.0  
1998 -1.0   1   8.629   35.0  
1999  0.0   1  12.626   52.0  
2000  0.0   1   8.147   50.0  
2001  1.0   1  13.210   88.0  
2002  1.0   1   9.016   32.0  
2003  1.0   1  12.155  152.0

In [17]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 179]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
2013  179   0     0   0.000000    0  43.0      1    1    0    0    0    0   
2014  179   0     1   0.000000    0  43.0      1    1    1    0    0    0   
2015  179   1     0   6.016438    0  43.0      1    1    0    0    0    0   
2016  179   1     1   6.016438    0  43.0      1    1    1    0    0    0   
2017  179   2     0  12.230137    0  43.0      1    1    0    0    0    0   
2018  179   2     1  12.230137    0  43.0      1    1    1    0    0    0   
2019  179   3     0  18.213699    0  43.0      1    1    0    0    0    0   
2020  179   3     1  18.213699    0  43.0      1    1    1    0    0    0   
2021  179   4     0  24.328767    0  43.0      1    1    0    0    0    0   
2022  179   4     1  24.328767    0  43.0      1    1    1    0    0    0   
2023  179   5     0  30.147945    0  43.0      1    1    0    0    0    0   
2024  179   5     1  30.147945    0  43.0      1    1    1    0    0    0   
2025  179   6     0  36.821918    0  43.0      1    1    0    0    0    0   
2026  179   6     1  36.821918    0  43.0      1    1    1    0    0    0   
2027  179   7     0  41.424658    0  43.0      1    1    0    0    0    0   
2028  179   7     1  41.424658    0  43.0      1    1    1    0    0    0   
2029  179   8     0  47.408219    0  43.0      1    1    0    0    0    0   
2030  179   8     1  47.408219    0  43.0      1    1    1    0    0    0   
2031  179   9     0  54.016438    0  43.0      1    1    0    0    0    0   
2032  179   9     1  54.016438    0  43.0      1    1    1    0    0    0   

      REL  DD   AREA  ANGLE  
2013  0.0   1  2.350    0.0  
2014  0.0   1  4.600   65.0  
2015  0.0   1  2.700    0.0  
2016  0.0   1  3.350   60.0  
2017  0.0   1  1.500    0.0  
2018  0.0   1  3.660   54.0  
2019  0.0   1  1.450    0.0  
2020  0.0   1  3.380   58.0  
2021  1.0   1  1.783    0.0  
2022  1.0   1  3.350   38.0  
2023  0.0   1  4.260    0.0  
2024  0.0   1  5.555   26.0  
2025 -1.0   1  4.420    0.0  
2026 -1.0   1  5.537   44.0  
2027 -1.0   1  5.630    0.0  
2028 -1.0   1  7.200   20.0  
2029 -1.0   1  5.947    8.0  
2030 -1.0   1  7.910   36.0  
2031 -1.0   1  6.460   16.0  
2032 -1.0   1  5.797   36.0

In [18]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 183]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
2073  183   0     1   0.000000    0  68.0      1    1    1    0    0    0   
2074  183   1     1   5.884932    0  68.0      1    1    1    0    0    0   
2075  183   2     1  12.065753    0  68.0      1    1    1    0    0    0   
2076  183   3     1  18.509589    0  68.0      1    1    1    0    0    0   
2077  183   4     1  24.295890    0  68.0      1    1    1    0    0    0   
2078  183   5     1  34.849315    0  68.0      1    1    1    0    0    0   
2079  183   6     1  41.523288    0  68.0      1    1    1    0    0    0   
2080  183   7     1  54.871233    0  68.0      1    1    1    0    0    0   

      REL  DD   AREA  ANGLE  
2073  0.0   1  0.000    0.0  
2074  0.0   1  3.850    0.0  
2075  0.0   1  4.438    0.0  
2076  0.0   1  5.617    0.0  
2077  0.0   1  7.350    0.0  
2078 -1.0   1  7.228    0.0  
2079 -1.0   1  7.337    6.0  
2080  0.0   1  5.800    4.0

In [19]:
dd_df[dd_df['ID'] == 243]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
2698  243   0     0   0.000000    0  63.0      0    1    0    0    0    0   
2699  243   1     0   5.852055    0  63.0      0    1    0    0    0    0   
2700  243   2     0  11.934247    0  63.0      0    1    0    0    0    0   
2701  243   3     0  17.950685    0  63.0      0    1    0    0    0    0   
2702  243   4     0  23.901370    0  63.0      0    1    0    0    0    0   
2703  243   5     0  30.641096    0  63.0      0    1    0    0    0    0   
2704  243   6     0  36.328767    0  63.0      0    1    0    0    0    0   
2705  243   7     0  42.312329    0  63.0      0    1    0    0    0    0   
2706  243   8     0  47.243836    0  63.0      0    1    0    0    0    0   
2707  243   9     0  54.410959    0  63.0      0    1    0    0    0    0   

      REL  DD    AREA  ANGLE  
2698  0.0   1   3.520    0.0  
2699  0.0   1   7.867    0.0  
2700  0.0   1   8.230    0.0  
2701  0.0   1   7.115    0.0  
2702  0.0   1   6.332    0.0  
2703 -1.0   1   8.905    0.0  
2704  0.0   1   8.938    0.0  
2705  0.0   1  10.167    0.0  
2706  0.0   1  10.563    0.0  
2707  0.0   1  11.559    6.0

## Analysis of the ID's with inconsistencies in the REL field (false and true at the same time)

I analyzed one by one the suspicious elements.

### Results
- 2: Only one followup with REL = 0. FIX by setting all to 1.
- 9: Has one missing value. FIX by setting all to 0.
- 12: Hard to say. Initially, it is set to 0, then there is one "outlier" at FU=3. Also at the end the patient reports REL=1. Maybe at the end a relative got the disease. CHECK IN DETAIL.
- 20: Just a missing value problem. FIX by setting all to 1.
- 24: Hard to say. In the last FU it reports REL=1. All others are REL=0.
- 32: Hard to say. One ontlier in follow yp 1. CHECK IN DETAIL.
- 35: No real problem, but better to CHECK IN DETAIL.
- 38: FIX: I would say set all to 1.
- 67: FIX: I would say set all to 0.
- 85: Looks ok... But with 2 values
- 93: One outlier at the beginning. FIX: Set first value to 0.
- 104: Not sure if the first one is outlier :(. CHECK IN DETAIL.
- 108: I would say set all to 0.
- 130: I would say it is ok, but has to values :(
- 151: Just one missing vlaue. FIX: Set all to 0.
- 154: Small dataset. Set all to 0.
- 168: One different value at FU=0. FIX: I would say set all to 0.
- 174: Just one missing value. Set all to 0.
- 177: Missing values + 0 and 1. I would say to set the missing values to 0.
- 179: HARD TO SAY. Check in detail.
- 182: Outlier. Set all to 1.
- 183: Just missing value. SET all to 0.
- 218: I would say to set all to 1.
- 221: Looks ok, but 2 values :(
- 223: I would say to set all to 0. CHECK.
- 235: Looks ok. Maybe set all to 1. CHECK!
- 237: Looks ok, but two values :(
- 243: Missing value. FIX: set all to 0.
- 247: NO IDEA! :(
- 248: I would say set all to 0. CHECK.

In [20]:
elements = [2, 9, 12, 20, 24, 32, 35, 38, 67, 85, 93, 104, 108, 130, 151, 154, 168, 174, 177, 179, 182, 183,
           218, 221, 223, 235, 237, 243, 247, 248]

dd_df[dd_df['ID'] == 248]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
2749  248   0     0   0.000000    1  77.0      0    1    1    0    0    0   
2750  248   0     1   0.000000    1  77.0      0    1    1    0    0    0   
2751  248   1     0   7.167123    1  77.0      0    1    1    0    0    0   
2752  248   1     1   7.167123    1  77.0      0    1    1    0    0    0   
2753  248   2     0  30.378082    1  77.0      0    1    1    0    0    0   
2754  248   2     1  30.378082    1  77.0      0    1    1    0    0    0   

      REL  DD   AREA  ANGLE  
2749  1.0   0  0.000    0.0  
2750  1.0   1  1.360    0.0  
2751  0.0   0  0.000    0.0  
2752  0.0   1  1.430    0.0  
2753  0.0   1  0.850    0.0  
2754  0.0   1  1.907    0.0

## Analysis of having measurements of both hands


In [21]:
grouped = dd_df.groupby(['ID', 'Hand'])
grouped.count()

FU  MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  DD  AREA  \
ID  Hand                                                                        
2   0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   10   10   10   10   10   10  10    10   
3   0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   10   10   10   10   10   10  10    10   
4   0      8      8    8     8      8    8    8    8    8    8    8   8     8   
    1      8      8    8     8      8    8    8    8    8    8    8   8     8   
6   0      7      7    7     7      7    7    7    7    7    7    7   7     7   
    1      7      7    7     7      7    7    7    7    7    7    7   7     7   
7   0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   10   10   10   10   10   10  10    10   
8   0      5      5    5     5      5    5    5    5    5    5    5   5     5   
    1      5      5    5     5      5    5    5    5    5    5    5   5     5   
9   0      1      1    1     1      1    1    1    1    1    1    1   1     1   
    1      8      8    8     8      8    8    8    8    8    8    8   8     8   
10  0      6      6    6     6      6    6    6    6    6    6    6   6     6   
    1      6      6    6     6      6    6    6    6    6    6    6   6     6   
11  0      6      6    6     6      6    6    6    6    6    6    6   6     6   
    1      6      6    6     6      6    6    6    6    6    6    6   6     6   
12  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   10   10   10   10   10   10  10    10   
14  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
15  1      3      3    3     3      3    3    3    3    3    3    3   3     3   
16  0      6      6    6     6      6    6    6    6    6    6    6   6     6   
17  0      3      3    3     3      3    3    3    3    3    3    3   3     3   
    1      3      3    3     3      3    3    3    3    3    3    3   3     3   
19  0      5      5    5     5      5    5    5    5    5    5    5   5     5   
    1      5      5    5     5      5    5    5    5    5    5    5   5     5   
20  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
21  0      3      3    3     3      3    3    3    3    3    3    3   3     3   
    1      3      3    3     3      3    3    3    3    3    3    3   3     3   
23  0      6      6    6     6      6    6    6    6    6    6    6   6     6   
24  0      8      8    8     8      8    8    8    8    8    8    8   8     8   
    1      8      8    8     8      8    8    8    8    8    8    8   8     8   
25  1      4      4    4     4      4    4    4    4    4    4    4   4     4   
26  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
27  0      9      9    9     9      9    9    9    9    9    9    9   9     9   
    1      9      9    9     9      9    9    9    9    9    9    9   9     9   
28  0      9      9    9     9      9    9    9    9    9    9    9   9     9   
    1      9      9    9     9      9    9    9    9    9    9    9   9     9   
30  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   10   10   10   10   10   10  10    10   
31  1     10     10   10    10     10   10   10   10   10   10   10  10    10   
32  0      8      8    8     8      8    8    8    8    8    8    8   8     8   
    1      8      8    8     8      8    8    8    8    8    8    8   8     8   
33  0      9      9    9     9      9    9    9    9    9    9    9   9     9   
    1      9      9    9     9      9    9    9    9    9    9    9   9     9   
34  0     10     10   10    10     10   10   10   10   10   10   10  10    10   
    1     10     10   10    10     10   1

In [22]:
grouped = dd_df.groupby(['ID', 'FU'])
grouped.count()

Hand  MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL  DD  AREA  \
ID  FU                                                                          
2   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2    2    2    2    2    2    2   2     2   
    3      2      2    2     2      2    2    2    2    2    2    2   2     2   
    4      2      2    2     2      2    2    2    2    2    2    2   2     2   
    5      2      2    2     2      2    2    2    2    2    2    2   2     2   
    6      2      2    2     2      2    2    2    2    2    2    2   2     2   
    7      2      2    2     2      2    2    2    2    2    2    2   2     2   
    8      2      2    2     2      2    2    2    2    2    2    2   2     2   
    9      2      2    2     2      2    2    2    2    2    2    2   2     2   
3   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2    2    2    2    2    2    2   2     2   
    3      2      2    2     2      2    2    2    2    2    2    2   2     2   
    4      2      2    2     2      2    2    2    2    2    2    2   2     2   
    5      2      2    2     2      2    2    2    2    2    2    2   2     2   
    6      2      2    2     2      2    2    2    2    2    2    2   2     2   
    7      2      2    2     2      2    2    2    2    2    2    2   2     2   
    8      2      2    2     2      2    2    2    2    2    2    2   2     2   
    9      2      2    2     2      2    2    2    2    2    2    2   2     2   
4   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2    2    2    2    2    2    2   2     2   
    3      2      2    2     2      2    2    2    2    2    2    2   2     2   
    4      2      2    2     2      2    2    2    2    2    2    2   2     2   
    5      2      2    2     2      2    2    2    2    2    2    2   2     2   
    6      2      2    2     2      2    2    2    2    2    2    2   2     2   
    7      2      2    2     2      2    2    2    2    2    2    2   2     2   
6   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2    2    2    2    2    2    2   2     2   
    3      2      2    2     2      2    2    2    2    2    2    2   2     2   
    4      2      2    2     2      2    2    2    2    2    2    2   2     2   
    5      2      2    2     2      2    2    2    2    2    2    2   2     2   
    6      2      2    2     2      2    2    2    2    2    2    2   2     2   
7   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2    2    2    2    2    2    2   2     2   
    3      2      2    2     2      2    2    2    2    2    2    2   2     2   
    4      2      2    2     2      2    2    2    2    2    2    2   2     2   
    5      2      2    2     2      2    2    2    2    2    2    2   2     2   
    6      2      2    2     2      2    2    2    2    2    2    2   2     2   
    7      2      2    2     2      2    2    2    2    2    2    2   2     2   
    8      2      2    2     2      2    2    2    2    2    2    2   2     2   
    9      2      2    2     2      2    2    2    2    2    2    2   2     2   
8   0      2      2    2     2      2    2    2    2    2    2    2   2     2   
    1      2      2    2     2      2    2    2    2    2    2    2   2     2   
    2      2      2    2     2      2  

In [45]:
subset = dd_df[dd_df['FU'] > 8 ]
print(len(subset['ID'].unique()))
print(subset['ID'].unique())
subset

113
[  2   3   7  12  14  20  26  30  31  34  35  36  37  40  41  42  44  46
  47  48  50  51  52  53  56  57  58  59  62  63  64  66  67  70  71  72
  79  80  82  83  84  85  86  88  93  94  95  96 100 103 104 108 111 115
 116 123 124 125 127 130 131 132 136 138 142 148 150 151 156 157 158 159
 164 165 167 171 172 173 174 179 180 182 185 188 189 193 195 197 199 202
 205 209 213 214 216 218 220 221 226 229 230 231 232 233 235 240 243 244
 245 250 251 254 256]


ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
18      2   9     0  53.621918    0  81.0      1    1    0    0    0    0   
19      2   9     1  53.621918    0  81.0      1    1    0    0    0    0   
38      3   9     0  53.589041    0  64.0      0    1    1    0    0    0   
39      3   9     1  53.589041    0  64.0      0    1    0    0    0    0   
88      7   9     0  53.720548    1  59.0      1    1    0    0    0    0   
89      7   9     1  53.720548    1  59.0      1    1    1    0    0    0   
151    12   9     0  54.312329    0  62.0      0    1    1    0    0    0   
152    12   9     1  54.312329    0  62.0      0    1    0    0    0    0   
162    14   9     0  52.767123    0  56.0      0    1    0    0    0    0   
197    20   9     0  53.424658    1  57.0      1    1    0    0    0    0   
239    26   9     0  53.128767    1  63.0      1    1    0    0    0    0   
294    30   9     0  53.654795    1  69.0      0    0    0    0    0    0   
295    30   9     1  53.654795    1  69.0      0    0    0    0    0    0   
305    31   9     1  55.758904    0  49.0      1    1    0    0    0    0   
358    34   9     0  53.621918    1  58.0      1    1    1    0    0    0   
359    34   9     1  53.621918    1  58.0      1    1    0    0    0    0   
378    35   9     0  53.227397    1  62.0      0    1    1    0    0    1   
379    35   9     1  53.227397    1  62.0      0    1    0    0    0    1   
389    36   9     0  53.194521    0  48.0      0    1    0    0    0    0   
399    37   9     1  53.654795    0  69.0      1    1    1    0    0    0   
434    40   9     0  53.950685    0  64.0      1    1    1    0    0    0   
435    40   9     1  53.950685    0  64.0      1    1    0    0    0    0   
445    41   9     0  50.860274    1  69.0      1    1    1    0    0    0   
464    42   9     0  53.391781    0  57.0      1    1    1    0    0    0   
465    42   9     1  53.391781    0  57.0      1    1    1    0    0    0   
484    44   9     0  53.227397    0  69.0      1    1    0    0    0    0   
485    44   9     1  53.227397    0  69.0      1    1    1    0    0    0   
514    46   9     0  53.654795    0  68.0      1    1    0    0    1    0   
515    46   9     1  53.654795    0  68.0      1    1    0    0    1    0   
534    47   9     0  53.128767    1  65.0      1    1    1    0    0    0   
535    47   9     1  53.128767    1  65.0      1    1    1    0    0    0   
554    48   9     0  54.049315    0  78.0      1    1    1    0    0    0   
555    48   9     1  54.049315    0  78.0      1    1    0    0    0    0   
576    50   9     0  54.345205    1  64.0      1    1    1    1    0    0   
577    50   9     1  54.345205    1  64.0      1    1    1    1    0    0   
596    51   9     0  53.819178    1  87.0      0    1    0    0    0    0   
597    51   9     1  53.819178    1  87.0      0    1    1    0    0    0   
607    52   9     0  54.115068    0  70.0      1    1    0    0    0    0   
626    53   9     0  46.915068    0  40.0      0    1    1    0    0    0   
627    53   9     1  46.915068    0  40.0      0    1    1    0    0    0   
628    53  10     0  53.621918    0  40.0      0    1    1    0    0    0   
629    53  10     1  53.621918    0  40.0      0    1    1    0    0    0   
655    56   9     1  36.098630    1  58.0      1    1    0    0    0    0   
656    56  10     1  42.082192    1  58.0      1    1    0    0    0    0   
657    56  11     1  47.835616    1  58.0      1    1    0    0    0    0   
658    56  12     1  53.852055    1  58.0      1    1    0    0    0    0   
677    57   9     0  53.424658    0  64.0      1    1    0    0    0    0   
678    57   9     1  53.424658    0  64.0      1    1    0    0    0    0   
697    58   9     0  53.556164    0  62.0      1    1    1    0    0    0   
698    58   9     1  53.556164    0  62.0      1    1    1    0    0    0   
717    59   9     0  53.983562    1  68.0      1    1    1    0    0    0   
718

In [39]:
subset_fixed = dd_df[dd_df['FU'] <= 8 ]
print(len(subset_fixed['ID'].unique()))
print(subset_fixed['ID'].unique())
subset_fixed


224
[  2   3   4   6   7   8   9  10  11  12  14  15  16  17  19  20  21  23
  24  25  26  27  28  30  31  32  33  34  35  36  37  38  40  41  42  44
  45  46  47  48  49  50  51  52  53  54  56  57  58  59  60  62  63  64
  65  66  67  68  70  71  72  73  74  75  76  78  79  80  81  82  83  84
  85  86  87  88  90  92  93  94  95  96  97  98 100 101 102 103 104 105
 107 108 109 110 111 112 113 114 115 116 117 119 120 121 123 124 125 126
 127 128 130 131 132 134 135 136 137 138 139 140 141 142 143 145 146 147
 148 149 150 151 152 153 154 156 157 158 159 160 161 162 164 165 166 167
 168 170 171 172 173 174 177 178 179 180 182 183 184 185 186 187 188 189
 190 191 193 195 196 197 198 199 200 201 202 203 205 206 207 208 209 210
 212 213 214 215 216 218 219 220 221 223 224 225 226 227 228 229 230 231
 232 233 234 235 236 237 239 240 241 242 243 244 245 246 247 248 249 250
 251 252 253 254 255 256 257 258]


ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
0       2   0     0   0.000000    0  81.0      1    1    0    0    0    0   
1       2   0     1   0.000000    0  81.0      1    1    0    0    0    0   
2       2   1     0   5.753425    0  81.0      1    1    0    0    0    0   
3       2   1     1   5.753425    0  81.0      1    1    0    0    0    0   
4       2   2     0  11.736986    0  81.0      1    1    0    0    0    0   
5       2   2     1  11.736986    0  81.0      1    1    0    0    0    0   
6       2   3     0  17.950685    0  81.0      1    1    0    0    0    0   
7       2   3     1  17.950685    0  81.0      1    1    0    0    0    0   
8       2   4     0  23.934247    0  81.0      1    1    0    0    0    0   
9       2   4     1  23.934247    0  81.0      1    1    0    0    0    0   
10      2   5     0  29.687671    0  81.0      1    1    0    0    0    0   
11      2   5     1  29.687671    0  81.0      1    1    0    0    0    0   
12      2   6     0  36.164384    0  81.0      1    1    0    0    0    0   
13      2   6     1  36.164384    0  81.0      1    1    0    0    0    0   
14      2   7     0  41.391781    0  81.0      1    1    0    0    0    0   
15      2   7     1  41.391781    0  81.0      1    1    0    0    0    0   
20      3   0     0   0.000000    0  64.0      0    1    1    0    0    0   
21      3   0     1   0.000000    0  64.0      0    1    0    0    0    0   
22      3   1     0   6.049315    0  64.0      0    1    1    0    0    0   
23      3   1     1   6.049315    0  64.0      0    1    0    0    0    0   
24      3   2     0  12.197260    0  64.0      0    1    1    0    0    0   
25      3   2     1  12.197260    0  64.0      0    1    0    0    0    0   
26      3   3     0  18.410959    0  64.0      0    1    1    0    0    0   
27      3   3     1  18.410959    0  64.0      0    1    0    0    0    0   
28      3   4     0  24.164384    0  64.0      0    1    1    0    0    0   
29      3   4     1  24.164384    0  64.0      0    1    0    0    0    0   
30      3   5     0  30.147945    0  64.0      0    1    1    0    0    0   
31      3   5     1  30.147945    0  64.0      0    1    0    0    0    0   
32      3   6     0  35.934247    0  64.0      0    1    1    0    0    0   
33      3   6     1  35.934247    0  64.0      0    1    0    0    0    0   
34      3   7     0  41.917808    0  64.0      0    1    1    0    0    0   
35      3   7     1  41.917808    0  64.0      0    1    0    0    0    0   
40      4   0     0   0.000000    1  67.0      0    1    0    0    0    0   
41      4   0     1   0.000000    1  67.0      0    1    1    0    0    0   
42      4   1     0   5.753425    1  67.0      0    1    0    0    0    0   
43      4   1     1   5.753425    1  67.0      0    1    1    0    0    0   
44      4   2     0  11.112329    1  67.0      0    1    0    0    0    0   
45      4   2     1  11.112329    1  67.0      0    1    1    0    0    0   
46      4   3     0  17.161644    1  67.0      0    1    0    0    0    0   
47      4   3     1  17.161644    1  67.0      0    1    1    0    0    0   
48      4   4     0  22.915068    1  67.0      0    1    0    0    0    0   
49      4   4     1  22.915068    1  67.0      0    1    1    0    0    0   
50      4   5     0  29.917808    1  67.0      0    1    0    0    0    0   
51      4   5     1  29.917808    1  67.0      0    1    1    0    0    0   
52      4   6     0  36.131507    1  67.0      0    1    0    0    0    0   
53      4   6     1  36.131507    1  67.0      0    1    1    0    0    0   
54      4   7     0  41.490411    1  67.0      0    1    0    0    0    0   
55      4   7     1  41.490411    1  67.0      0    1    1    0    0    0   
56      6   0     0   0.000000    0  80.0      1    0    1    1    0    0   
57      6   0     1   0.000000    0  80.0      1    0    1    1    0    0   
58      6   1     0   5.950685    0  80.0      1    0    1    1    0    0   
59 

In [31]:
dd_df[dd_df['ID'] == 151 ]

ID  FU  Hand      MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  \
1719  151   0     0   0.000000    0  75.0      1    1    0    0    0    0   
1720  151   0     1   0.000000    0  75.0      1    1    0    0    0    0   
1721  151   1     0   4.964384    0  75.0      1    1    0    0    0    0   
1722  151   1     1   4.964384    0  75.0      1    1    0    0    0    0   
1723  151   2     0  10.882192    0  75.0      1    1    0    0    0    0   
1724  151   2     1  10.882192    0  75.0      1    1    0    0    0    0   
1725  151   3     0  16.865753    0  75.0      1    1    0    0    0    0   
1726  151   3     1  16.865753    0  75.0      1    1    0    0    0    0   
1727  151   4     0  22.849315    0  75.0      1    1    0    0    0    0   
1728  151   4     1  22.849315    0  75.0      1    1    0    0    0    0   
1729  151   5     0  25.315068    0  75.0      1    1    0    0    0    0   
1730  151   5     1  25.315068    0  75.0      1    1    0    0    0    0   
1731  151   6     0  28.142466    0  75.0      1    1    0    0    0    0   
1732  151   7     0  34.126027    0  75.0      1    1    0    0    0    0   
1733  151   8     0  40.142466    0  75.0      1    1    0    0    0    0   
1734  151   9     0  46.553425    0  75.0      1    1    0    0    0    0   

      REL  DD   AREA  ANGLE  
1719  0.0   1  4.723   10.0  
1720  0.0   1  2.660   35.0  
1721  0.0   1  3.760   14.0  
1722  0.0   1  4.567   42.0  
1723  0.0   1  4.810   16.0  
1724  0.0   1  4.290    0.0  
1725  0.0   1  4.875   16.0  
1726  0.0   1  3.850   52.0  
1727  0.0   1  5.195    0.0  
1728  0.0   1  3.187   64.0  
1729 -1.0   1  5.830    0.0  
1730 -1.0   1  4.417   62.0  
1731  0.0   1  5.980   10.0  
1732  0.0   1  6.465   18.0  
1733  0.0   1  6.985   14.0  
1734  0.0   1  6.250   14.0

In [41]:
subset.groupby(['Hand']).count()

ID   FU  MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  REL   DD  \
Hand                                                                         
0     198  198    198  198   198    198  198  198  198  198  198  198  198   
1     212  212    212  212   212    212  212  212  212  212  212  212  212   

      AREA  ANGLE  
Hand               
0      198    198  
1      212    212

In [42]:
hand0 = subset[subset['Hand'] == 0 ]['ID'].unique()
hand1 = subset[subset['Hand'] == 1 ]['ID'].unique()
diff = np.setdiff1d(hand0, hand1)
print(len(diff))
diff

27


array([ 14,  20,  26,  36,  41,  52,  63,  85,  93,  96, 109, 115, 124,
       134, 143, 151, 174, 178, 185, 188, 193, 213, 220, 224, 243, 250, 251])

In [43]:
hand0 = subset[subset['Hand'] == 0 ]['ID'].unique()
hand0

array([  2,   3,   7,  12,  14,  20,  26,  27,  28,  30,  33,  34,  35,
        36,  40,  41,  42,  44,  46,  47,  48,  50,  51,  52,  53,  57,
        58,  59,  62,  63,  64,  67,  70,  71,  72,  73,  79,  82,  84,
        85,  88,  93,  94,  95,  96, 102, 103, 104, 108, 109, 115, 116,
       120, 124, 125, 127, 130, 131, 132, 134, 136, 138, 140, 143, 145,
       149, 151, 157, 158, 159, 170, 172, 173, 174, 178, 179, 180, 182,
       185, 188, 189, 193, 196, 197, 208, 212, 213, 216, 220, 224, 226,
       229, 230, 231, 232, 233, 235, 237, 240, 241, 243, 249, 250, 251,
       254, 256])

In [44]:
hand1 = subset[subset['Hand'] == 1 ]['ID'].unique()
hand1

array([  2,   3,   7,  12,  27,  28,  30,  31,  33,  34,  35,  37,  40,
        42,  44,  46,  47,  48,  50,  51,  53,  56,  57,  58,  59,  62,
        64,  66,  67,  70,  71,  72,  73,  79,  80,  82,  83,  84,  86,
        88,  94,  95, 100, 102, 103, 104, 108, 111, 112, 116, 117, 120,
       123, 125, 127, 130, 131, 132, 136, 138, 140, 142, 145, 148, 149,
       150, 153, 156, 157, 158, 159, 164, 165, 167, 170, 171, 172, 173,
       179, 180, 182, 189, 191, 195, 196, 197, 199, 202, 205, 208, 209,
       212, 214, 216, 218, 221, 226, 229, 230, 231, 232, 233, 234, 235,
       237, 240, 241, 244, 245, 249, 254, 256])